# Shared source scanner for evidence guards. Non-code characters become spaces
# while line endings and source length remain unchanged, so brace offsets stay valid.
function(evidence_is_cpp_splice source index output)
    string(ASCII 10 newline)
    string(ASCII 13 carriage_return)
    string(ASCII 92 backslash)
    string(LENGTH "${source}" source_length)
    if(index GREATER_EQUAL source_length)
        set(${output} FALSE PARENT_SCOPE)
        return()
    endif()
    string(SUBSTRING "${source}" ${index} 1 character)
    if(NOT character STREQUAL "${backslash}")
        set(${output} FALSE PARENT_SCOPE)
        return()
    endif()
    math(EXPR next_index "${index} + 1")
    if(next_index GREATER_EQUAL source_length)
        set(${output} FALSE PARENT_SCOPE)
        return()
    endif()
    string(SUBSTRING "${source}" ${next_index} 1 next_character)
    if(next_character STREQUAL "${newline}")
        set(${output} TRUE PARENT_SCOPE)
        return()
    endif()
    math(EXPR after_next_index "${index} + 2")
    if(next_character STREQUAL "${carriage_return}"
            AND after_next_index LESS source_length)
        string(SUBSTRING "${source}" ${after_next_index} 1 after_next_character)
        if(after_next_character STREQUAL "${newline}")
            set(${output} TRUE PARENT_SCOPE)
            return()
        endif()
    endif()
    set(${output} FALSE PARENT_SCOPE)
endfunction()

function(evidence_cpp_logical_next_character source start output_character output_found)
    string(ASCII 10 newline)
    string(ASCII 13 carriage_return)
    string(LENGTH "${source}" source_length)
    set(probe ${start})
    while(probe LESS source_length)
        evidence_is_cpp_splice("${source}" ${probe} is_splice)
        if(is_splice)
            math(EXPR newline_index "${probe} + 1")
            string(SUBSTRING "${source}" ${newline_index} 1 splice_newline)
            if(splice_newline STREQUAL "${carriage_return}")
                math(EXPR probe "${probe} + 3")
            else()
                math(EXPR probe "${probe} + 2")
            endif()
        else()
            string(SUBSTRING "${source}" ${probe} 1 logical_character)
            set(${output_character} "${logical_character}" PARENT_SCOPE)
            set(${output_found} TRUE PARENT_SCOPE)
            return()
        endif()
    endwhile()
    set(${output_character} "" PARENT_SCOPE)
    set(${output_found} FALSE PARENT_SCOPE)
endfunction()

function(evidence_sanitize_cpp_for_scan source output)
    string(ASCII 10 newline)
    string(ASCII 13 carriage_return)
    string(ASCII 34 double_quote)
    string(ASCII 39 single_quote)
    string(ASCII 92 backslash)
    string(LENGTH "${source}" source_length)
    if(source_length EQUAL 0)
        set(${output} "" PARENT_SCOPE)
        return()
    endif()

    math(EXPR source_last "${source_length} - 1")
    set(sanitized "")
    set(scan_state code)
    set(escaped FALSE)
    foreach(character_index RANGE 0 ${source_last})
        string(SUBSTRING "${source}" ${character_index} 1 character)
        set(next_character "")
        set(next_found FALSE)
        if(character_index LESS source_last)
            math(EXPR next_character_index "${character_index} + 1")
            evidence_cpp_logical_next_character("${source}" ${next_character_index}
                next_character next_found)
        endif()

        if(scan_state STREQUAL "code")
            if(next_found AND character STREQUAL "/" AND next_character STREQUAL "/")
                set(scan_state line_comment)
                string(APPEND sanitized " ")
            elseif(next_found AND character STREQUAL "/" AND next_character STREQUAL "*")
                set(scan_state block_comment)
                string(APPEND sanitized " ")
            elseif(character STREQUAL "${double_quote}")
                set(scan_state string_literal)
                set(escaped FALSE)
                string(APPEND sanitized " ")
            elseif(character STREQUAL "${single_quote}")
                set(scan_state character_literal)
                set(escaped FALSE)
                string(APPEND sanitized " ")
            else()
                string(APPEND sanitized "${character}")
            endif()
        elseif(scan_state STREQUAL "line_comment")
            evidence_is_cpp_splice("${source}" ${character_index} is_splice)
            if(character STREQUAL "${backslash}" AND is_splice)
                set(scan_state line_comment_splice)
                string(APPEND sanitized " ")
            elseif(character STREQUAL "${newline}" OR character STREQUAL "${carriage_return}")
                set(scan_state code)
                string(APPEND sanitized "${character}")
            else()
                string(APPEND sanitized " ")
            endif()
        elseif(scan_state STREQUAL "line_comment_splice")
            if(character STREQUAL "${newline}")
                set(scan_state line_comment)
                string(APPEND sanitized "${character}")
            elseif(character STREQUAL "${carriage_return}")
                string(APPEND sanitized "${character}")
            else()
                message(FATAL_ERROR "Evidence scanner expected a line splice terminator")
            endif()
        elseif(scan_state STREQUAL "block_comment")
            if(character STREQUAL "*" AND next_found AND next_character STREQUAL "/")
                set(scan_state block_comment_close_pending)
            endif()
            if(character STREQUAL "${newline}" OR character STREQUAL "${carriage_return}")
                string(APPEND sanitized "${character}")
            else()
                string(APPEND sanitized " ")
            endif()
        elseif(scan_state STREQUAL "block_comment_close_pending")
            evidence_is_cpp_splice("${source}" ${character_index} is_splice)
            if(character STREQUAL "${backslash}" AND is_splice)
                set(scan_state block_comment_close_splice)
            elseif(character STREQUAL "/")
                set(scan_state code)
            endif()
            if(character STREQUAL "${newline}" OR character STREQUAL "${carriage_return}")
                string(APPEND sanitized "${character}")
            else()
                string(APPEND sanitized " ")
            endif()
        elseif(scan_state STREQUAL "block_comment_close_splice")
            if(character STREQUAL "${newline}")
                set(scan_state block_comment_close_pending)
                string(APPEND sanitized "${character}")
            elseif(character STREQUAL "${carriage_return}")
                string(APPEND sanitized "${character}")
            else()
                message(FATAL_ERROR "Evidence scanner expected a block-comment splice terminator")
            endif()
        elseif(scan_state STREQUAL "string_literal"
                OR scan_state STREQUAL "character_literal")
            evidence_is_cpp_splice("${source}" ${character_index} is_splice)
            if(character STREQUAL "${backslash}" AND is_splice)
                set(splice_return_state "${scan_state}")
                set(scan_state literal_splice)
            elseif(escaped)
                set(escaped FALSE)
            elseif(character STREQUAL "${backslash}")
                set(escaped TRUE)
            elseif((scan_state STREQUAL "string_literal" AND character STREQUAL "${double_quote}")
                    OR (scan_state STREQUAL "character_literal" AND character STREQUAL "${single_quote}"))
                set(scan_state code)
            endif()
            if(character STREQUAL "${newline}" OR character STREQUAL "${carriage_return}")
                string(APPEND sanitized "${character}")
            else()
                string(APPEND sanitized " ")
            endif()
        elseif(scan_state STREQUAL "literal_splice")
            if(character STREQUAL "${newline}")
                set(scan_state "${splice_return_state}")
                string(APPEND sanitized "${character}")
            elseif(character STREQUAL "${carriage_return}")
                string(APPEND sanitized "${character}")
            else()
                message(FATAL_ERROR "Evidence scanner expected a literal splice terminator")
            endif()
        endif()
    endforeach()
    set(${output} "${sanitized}" PARENT_SCOPE)
endfunction()

function(evidence_try_find_cpp_function_bounds_in_sanitized
        sanitized_source signature output_begin output_open output_end output_valid)
    set(${output_begin} -1 PARENT_SCOPE)
    set(${output_open} -1 PARENT_SCOPE)
    set(${output_end} -1 PARENT_SCOPE)
    set(${output_valid} FALSE PARENT_SCOPE)
    string(FIND "${sanitized_source}" "${signature}" function_begin)
    if(function_begin EQUAL -1)
        return()
    endif()
    string(SUBSTRING "${sanitized_source}" ${function_begin} -1 function_tail)
    string(FIND "${function_tail}" "{" brace_relative)
    if(brace_relative EQUAL -1)
        return()
    endif()
    set(parenthesis_depth 0)
    set(declaration_only FALSE)
    if(brace_relative GREATER 0)
        math(EXPR prefix_last "${brace_relative} - 1")
        foreach(prefix_index RANGE 0 ${prefix_last})
            string(SUBSTRING "${function_tail}" ${prefix_index} 1 character)
            if(character STREQUAL "(")
                math(EXPR parenthesis_depth "${parenthesis_depth} + 1")
            elseif(character STREQUAL ")")
                math(EXPR parenthesis_depth "${parenthesis_depth} - 1")
                if(parenthesis_depth LESS 0)
                    return()
                endif()
            elseif(character STREQUAL ";" AND parenthesis_depth EQUAL 0)
                set(declaration_only TRUE)
                break()
            endif()
        endforeach()
    endif()
    if(declaration_only OR NOT parenthesis_depth EQUAL 0)
        return()
    endif()
    math(EXPR brace_open "${function_begin} + ${brace_relative}")
    string(LENGTH "${sanitized_source}" source_length)
    math(EXPR source_last "${source_length} - 1")
    set(brace_depth 0)
    set(function_end -1)
    foreach(character_index RANGE ${brace_open} ${source_last})
        string(SUBSTRING "${sanitized_source}" ${character_index} 1 character)
        if(character STREQUAL "{")
            math(EXPR brace_depth "${brace_depth} + 1")
        elseif(character STREQUAL "}")
            math(EXPR brace_depth "${brace_depth} - 1")
            if(brace_depth EQUAL 0)
                set(function_end ${character_index})
                break()
            endif()
        endif()
    endforeach()
    if(function_end EQUAL -1)
        return()
    endif()
    set(${output_begin} ${function_begin} PARENT_SCOPE)
    set(${output_open} ${brace_open} PARENT_SCOPE)
    set(${output_end} ${function_end} PARENT_SCOPE)
    set(${output_valid} TRUE PARENT_SCOPE)
endfunction()

function(evidence_find_cpp_function_bounds_in_sanitized sanitized_source signature output_begin output_open output_end)
    evidence_try_find_cpp_function_bounds_in_sanitized(
        "${sanitized_source}" "${signature}"
        function_begin function_open function_end function_valid)
    if(NOT function_valid)
        message(FATAL_ERROR "Evidence validation function is missing: ${signature}")
    endif()
    set(${output_begin} ${function_begin} PARENT_SCOPE)
    set(${output_open} ${function_open} PARENT_SCOPE)
    set(${output_end} ${function_end} PARENT_SCOPE)
endfunction()

function(evidence_find_cpp_function_bounds source signature output_begin output_open output_end)
    evidence_sanitize_cpp_for_scan("${source}" sanitized_source)
    evidence_find_cpp_function_bounds_in_sanitized("${sanitized_source}" "${signature}"
        function_begin function_open function_end)
    set(${output_begin} ${function_begin} PARENT_SCOPE)
    set(${output_open} ${function_open} PARENT_SCOPE)
    set(${output_end} ${function_end} PARENT_SCOPE)
endfunction()

function(evidence_extract_cpp_function_block source signature output)
    evidence_sanitize_cpp_for_scan("${source}" sanitized_source)
    evidence_find_cpp_function_bounds_in_sanitized("${sanitized_source}" "${signature}"
        function_begin function_open function_end)
    math(EXPR function_length "${function_end} - ${function_begin} + 1")
    string(SUBSTRING "${sanitized_source}" ${function_begin} ${function_length}
        function_block)
    set(${output} "${function_block}" PARENT_SCOPE)
endfunction()

function(evidence_find_cpp_balanced_scope_end_in_sanitized
        source open_index output_end output_valid)
    string(LENGTH "${source}" source_length)
    set(${output_end} -1 PARENT_SCOPE)
    set(${output_valid} FALSE PARENT_SCOPE)
    if(open_index LESS 0 OR open_index GREATER_EQUAL source_length)
        return()
    endif()
    string(SUBSTRING "${source}" ${open_index} 1 open_character)
    if(NOT open_character STREQUAL "{")
        return()
    endif()
    set(cursor ${open_index})
    set(depth 0)
    while(cursor LESS source_length)
        string(SUBSTRING "${source}" ${cursor} -1 tail)
        string(FIND "${tail}" "{" next_open)
        string(FIND "${tail}" "}" next_close)
        if(next_close EQUAL -1)
            return()
        endif()
        if(NOT next_open EQUAL -1 AND next_open LESS next_close)
            math(EXPR cursor "${cursor} + ${next_open} + 1")
            math(EXPR depth "${depth} + 1")
        else()
            math(EXPR close_index "${cursor} + ${next_close}")
            math(EXPR depth "${depth} - 1")
            if(depth EQUAL 0)
                set(${output_end} ${close_index} PARENT_SCOPE)
                set(${output_valid} TRUE PARENT_SCOPE)
                return()
            endif()
            math(EXPR cursor "${close_index} + 1")
        endif()
    endwhile()
endfunction()

function(evidence_cpp_prefix_has_only_namespace_scopes_in_sanitized
        source prefix_end output_valid)
    if(prefix_end EQUAL 0)
        set(${output_valid} TRUE PARENT_SCOPE)
        return()
    endif()
    string(SUBSTRING "${source}" 0 ${prefix_end} prefix_source)
    string(LENGTH "${prefix_source}" prefix_length)
    if(prefix_length EQUAL 0)
        set(${output_valid} TRUE PARENT_SCOPE)
        return()
    endif()
    math(EXPR prefix_last "${prefix_length} - 1")
    set(scope_kinds)
    foreach(character_index RANGE 0 ${prefix_last})
        string(SUBSTRING "${prefix_source}" ${character_index} 1 character)
        if(character STREQUAL "{")
            string(SUBSTRING "${prefix_source}" 0 ${character_index}
                before_open)
            if(before_open MATCHES
                    "namespace([ \t\r\n]+[A-Za-z_][A-Za-z0-9_]*([ \t]*::[ \t]*[A-Za-z_][A-Za-z0-9_]*)*)?[ \t\r\n]*$")
                list(APPEND scope_kinds namespace)
            else()
                list(APPEND scope_kinds non_namespace)
            endif()
        elseif(character STREQUAL "}")
            list(LENGTH scope_kinds scope_depth)
            if(scope_depth EQUAL 0)
                set(${output_valid} FALSE PARENT_SCOPE)
                return()
            endif()
            list(POP_BACK scope_kinds)
        endif()
    endforeach()
    foreach(scope_kind IN LISTS scope_kinds)
        if(NOT scope_kind STREQUAL namespace)
            set(${output_valid} FALSE PARENT_SCOPE)
            return()
        endif()
    endforeach()
    set(${output_valid} TRUE PARENT_SCOPE)
endfunction()

function(evidence_cpp_contains_local_type_keyword_in_sanitized
        source output_contains)
    if(source MATCHES
            "(^|[^A-Za-z0-9_])(class|struct|union)([^A-Za-z0-9_]|$)")
        set(${output_contains} TRUE PARENT_SCOPE)
    else()
        set(${output_contains} FALSE PARENT_SCOPE)
    endif()
endfunction()

# Produces the potentially executable surface of an already-sanitized function.
# Statically dead controls and deferred lambda bodies are blanked without
# changing source length. A syntactic lambda IIFE (`}(`) is flattened into its
# caller's brace depth and recursively scanned, so nested deferred scopes still
# cannot lend evidence.
function(evidence_cpp_direct_execution_surface_in_sanitized source output)
    string(LENGTH "${source}" source_length)
    if(source_length EQUAL 0)
        set(${output} "" PARENT_SCOPE)
        return()
    endif()
    set(direct_source "")
    set(copy_cursor 0)
    set(dead_condition
        "(false|0[uUlL]*|![ \\t\\r\\n]*true|1[uUlL]*[ \\t\\r\\n]*==[ \\t\\r\\n]*0[uUlL]*|0[uUlL]*[ \\t\\r\\n]*==[ \\t\\r\\n]*1[uUlL]*)")
    while(copy_cursor LESS source_length)
        string(SUBSTRING "${source}" ${copy_cursor} -1 tail)
        string(REGEX MATCH
            "\\][ \\t\\r\\n]*(\\([^{};]*\\))?[ \\t\\r\\n]*((mutable|constexpr|consteval|static)[ \\t\\r\\n]*)*(noexcept([ \\t\\r\\n]*\\([^{};]*\\))?[ \\t\\r\\n]*)?(->[^{;]*)?[ \\t\\r\\n]*\\{"
            lambda_match "${tail}")
        string(REGEX MATCH
            "(if|while)[ \\t\\r\\n]*(constexpr[ \\t\\r\\n]*)?\\([ \\t\\r\\n]*${dead_condition}[ \\t\\r\\n]*\\)[ \\t\\r\\n]*(do[ \\t\\r\\n]*)?([^{;]*\\{|[^{};]*;)"
            dead_branch_match "${tail}")
        string(REGEX MATCH
            "for[ \\t\\r\\n]*\\([ \\t\\r\\n]*;[ \\t\\r\\n]*${dead_condition}[ \\t\\r\\n]*;[^)]*\\)[ \\t\\r\\n]*([^{;]*\\{|[^{};]*;)"
            dead_for_match "${tail}")

        set(scope_match "")
        set(scope_relative -1)
        set(scope_kind "")
        if(NOT lambda_match STREQUAL "")
            string(FIND "${tail}" "${lambda_match}" scope_relative)
            set(scope_match "${lambda_match}")
            set(scope_kind lambda)
        endif()
        foreach(dead_match_name IN ITEMS dead_branch_match dead_for_match)
            set(dead_match "${${dead_match_name}}")
            if(dead_match STREQUAL "")
                continue()
            endif()
            string(FIND "${tail}" "${dead_match}" dead_relative)
            if(scope_relative EQUAL -1 OR dead_relative LESS scope_relative)
                set(scope_match "${dead_match}")
                set(scope_relative ${dead_relative})
                set(scope_kind dead-control)
            endif()
        endforeach()
        if(scope_relative EQUAL -1)
            string(APPEND direct_source "${tail}")
            break()
        endif()

        string(FIND "${scope_match}" "{" open_in_match)
        math(EXPR match_index "${copy_cursor} + ${scope_relative}")
        if(open_in_match EQUAL -1)
            string(LENGTH "${scope_match}" scope_length)
            math(EXPR scope_end "${match_index} + ${scope_length} - 1")
        else()
            math(EXPR open_index "${match_index} + ${open_in_match}")
            evidence_find_cpp_balanced_scope_end_in_sanitized(
                "${source}" ${open_index} scope_end scope_valid)
            if(NOT scope_valid)
                message(FATAL_ERROR
                    "Evidence direct-execution surface has no closing brace")
            endif()
        endif()

        set(lambda_iife FALSE)
        if(scope_kind STREQUAL lambda AND NOT open_in_match EQUAL -1)
            math(EXPR suffix_cursor "${scope_end} + 1")
            while(suffix_cursor LESS source_length)
                string(SUBSTRING "${source}" ${suffix_cursor} 1 suffix_character)
                if(suffix_character MATCHES "[ \\t\\r\\n]")
                    math(EXPR suffix_cursor "${suffix_cursor} + 1")
                else()
                    break()
                endif()
            endwhile()
            if(suffix_cursor LESS source_length)
                string(SUBSTRING "${source}" ${suffix_cursor} 1 suffix_character)
                if(suffix_character STREQUAL "(")
                    set(lambda_iife TRUE)
                endif()
            endif()
        endif()

        if(lambda_iife)
            math(EXPR prefix_length "${open_index} - ${copy_cursor}")
            if(prefix_length GREATER 0)
                string(SUBSTRING "${source}" ${copy_cursor} ${prefix_length}
                    prefix_chunk)
                string(APPEND direct_source "${prefix_chunk}")
            endif()
            string(APPEND direct_source " ")
            math(EXPR body_begin "${open_index} + 1")
            math(EXPR body_length "${scope_end} - ${body_begin}")
            if(body_length GREATER 0)
                string(SUBSTRING "${source}" ${body_begin} ${body_length}
                    lambda_body)
                evidence_cpp_direct_execution_surface_in_sanitized(
                    "${lambda_body}" direct_lambda_body)
                string(APPEND direct_source "${direct_lambda_body}")
            endif()
            string(APPEND direct_source " ")
            math(EXPR copy_cursor "${scope_end} + 1")
            continue()
        endif()

        if(scope_kind STREQUAL dead-control)
            set(remove_begin ${match_index})
        else()
            set(remove_begin ${open_index})
        endif()
        math(EXPR copy_length "${remove_begin} - ${copy_cursor}")
        if(copy_length GREATER 0)
            string(SUBSTRING "${source}" ${copy_cursor} ${copy_length}
                copy_chunk)
            string(APPEND direct_source "${copy_chunk}")
        endif()
        math(EXPR masked_length "${scope_end} - ${remove_begin} + 1")
        string(SUBSTRING "${source}" ${remove_begin} ${masked_length}
            masked_chunk)
        string(REGEX REPLACE "[^\r\n]" " " masked_chunk "${masked_chunk}")
        string(APPEND direct_source "${masked_chunk}")
        math(EXPR copy_cursor "${scope_end} + 1")
    endwhile()
    set(${output} "${direct_source}" PARENT_SCOPE)
endfunction()

# Finds a token only when it begins in C++ code. This is intentionally a
# lexical state walk rather than regex comment stripping. It visits delimiters
# instead of every source character so a caller can prove a raw crop starts in
# code without paying for a full sanitized copy of a large translation unit.
function(evidence_find_cpp_from_offset source start token output)
    string(SUBSTRING "${source}" ${start} -1 source_tail)
    string(FIND "${source_tail}" "${token}" relative_position)
    if(relative_position EQUAL -1)
        set(${output} -1 PARENT_SCOPE)
    else()
        math(EXPR absolute_position "${start} + ${relative_position}")
        set(${output} ${absolute_position} PARENT_SCOPE)
    endif()
endfunction()

function(evidence_find_cpp_code_token source token output)
    string(ASCII 10 newline)
    string(ASCII 13 carriage_return)
    string(ASCII 34 double_quote)
    string(ASCII 39 single_quote)
    string(ASCII 92 backslash)
    string(LENGTH "${source}" source_length)
    set(scan 0)
    set(scan_state code)
    set(token_position -1)
    while(scan LESS source_length)
        evidence_find_cpp_from_offset("${source}" ${scan} "${token}" candidate)
        if(scan_state STREQUAL "code")
            set(next_marker -1)
            foreach(marker IN ITEMS "/" "${double_quote}" "${single_quote}")
                evidence_find_cpp_from_offset("${source}" ${scan} "${marker}" marker_position)
                if(NOT marker_position EQUAL -1
                        AND (next_marker EQUAL -1 OR marker_position LESS next_marker))
                    set(next_marker ${marker_position})
                endif()
            endforeach()
            if(NOT candidate EQUAL -1
                    AND (next_marker EQUAL -1 OR candidate LESS next_marker))
                set(token_position ${candidate})
                break()
            endif()
            if(next_marker EQUAL -1)
                break()
            endif()
            string(SUBSTRING "${source}" ${next_marker} 1 marker_character)
            if(marker_character STREQUAL "/")
                math(EXPR after_slash "${next_marker} + 1")
                evidence_cpp_logical_next_character("${source}" ${after_slash}
                    next_character next_found)
                if(next_found AND next_character STREQUAL "/")
                    set(scan_state line_comment)
                elseif(next_found AND next_character STREQUAL "*")
                    set(scan_state block_comment)
                endif()
            elseif(marker_character STREQUAL "${double_quote}")
                set(scan_state string_literal)
            else()
                set(scan_state character_literal)
            endif()
            math(EXPR scan "${next_marker} + 1")
        elseif(scan_state STREQUAL "line_comment")
            set(next_marker -1)
            foreach(marker IN ITEMS "${backslash}" "${newline}" "${carriage_return}")
                evidence_find_cpp_from_offset("${source}" ${scan} "${marker}" marker_position)
                if(NOT marker_position EQUAL -1
                        AND (next_marker EQUAL -1 OR marker_position LESS next_marker))
                    set(next_marker ${marker_position})
                endif()
            endforeach()
            if(next_marker EQUAL -1)
                break()
            endif()
            string(SUBSTRING "${source}" ${next_marker} 1 marker_character)
            if(marker_character STREQUAL "${backslash}")
                evidence_is_cpp_splice("${source}" ${next_marker} is_splice)
                if(is_splice)
                    math(EXPR after_backslash "${next_marker} + 1")
                    string(SUBSTRING "${source}" ${after_backslash} 1 splice_character)
                    if(splice_character STREQUAL "${carriage_return}")
                        math(EXPR scan "${next_marker} + 3")
                    else()
                        math(EXPR scan "${next_marker} + 2")
                    endif()
                    continue()
                endif()
            elseif(marker_character STREQUAL "${newline}"
                    OR marker_character STREQUAL "${carriage_return}")
                set(scan_state code)
            endif()
            math(EXPR scan "${next_marker} + 1")
        elseif(scan_state STREQUAL "block_comment")
            evidence_find_cpp_from_offset("${source}" ${scan} "*" next_marker)
            if(next_marker EQUAL -1)
                break()
            endif()
            math(EXPR after_star "${next_marker} + 1")
            evidence_cpp_logical_next_character("${source}" ${after_star}
                next_character next_found)
            if(next_found AND next_character STREQUAL "/")
                set(scan_state code)
            endif()
            math(EXPR scan "${next_marker} + 1")
        else()
            if(scan_state STREQUAL "string_literal")
                set(quote_character "${double_quote}")
            else()
                set(quote_character "${single_quote}")
            endif()
            set(next_marker -1)
            foreach(marker IN ITEMS "${backslash}" "${quote_character}")
                evidence_find_cpp_from_offset("${source}" ${scan} "${marker}" marker_position)
                if(NOT marker_position EQUAL -1
                        AND (next_marker EQUAL -1 OR marker_position LESS next_marker))
                    set(next_marker ${marker_position})
                endif()
            endforeach()
            if(next_marker EQUAL -1)
                break()
            endif()
            string(SUBSTRING "${source}" ${next_marker} 1 marker_character)
            if(marker_character STREQUAL "${backslash}")
                evidence_is_cpp_splice("${source}" ${next_marker} is_splice)
                if(is_splice)
                    math(EXPR after_backslash "${next_marker} + 1")
                    string(SUBSTRING "${source}" ${after_backslash} 1 splice_character)
                    if(splice_character STREQUAL "${carriage_return}")
                        math(EXPR scan "${next_marker} + 3")
                    else()
                        math(EXPR scan "${next_marker} + 2")
                    endif()
                else()
                    math(EXPR scan "${next_marker} + 2")
                endif()
            else()
                set(scan_state code)
                math(EXPR scan "${next_marker} + 1")
            endif()
        endif()
    endwhile()
    set(${output} ${token_position} PARENT_SCOPE)
endfunction()

function(evidence_count_cpp_identifier source identifier output)
    string(REGEX REPLACE "[^A-Za-z0-9_]" ";" identifier_tokens
        "${source}")
    set(identifier_count 0)
    foreach(identifier_token IN LISTS identifier_tokens)
        if("${identifier_token}" STREQUAL "${identifier}")
            math(EXPR identifier_count "${identifier_count} + 1")
        endif()
    endforeach()
    set(${output} ${identifier_count} PARENT_SCOPE)
endfunction()

function(evidence_cpp_normalize_token_whitespace source output)
    string(REGEX REPLACE "[ \t\r\n]+" " " normalized "${source}")
    foreach(punctuation IN ITEMS
            "(" ")" "{" "}" "[" "]" "," ":" "&" "*" "<" ">" "=" "!")
        string(REPLACE " ${punctuation}" "${punctuation}"
            normalized "${normalized}")
        string(REPLACE "${punctuation} " "${punctuation}"
            normalized "${normalized}")
    endforeach()
    string(STRIP "${normalized}" normalized)
    set(${output} "${normalized}" PARENT_SCOPE)
endfunction()

function(evidence_count_literal_occurrences source literal output)
    string(LENGTH "${literal}" literal_length)
    if(literal_length EQUAL 0)
        set(${output} 0 PARENT_SCOPE)
        return()
    endif()
    string(LENGTH "${source}" source_length)
    string(REPLACE "${literal}" "" without_literal "${source}")
    string(LENGTH "${without_literal}" without_literal_length)
    math(EXPR occurrence_count
        "(${source_length} - ${without_literal_length}) / ${literal_length}")
    set(${output} ${occurrence_count} PARENT_SCOPE)
endfunction()

function(evidence_cpp_brace_depth_at source position output)
    if(position LESS_EQUAL 0)
        set(${output} 0 PARENT_SCOPE)
        return()
    endif()
    string(SUBSTRING "${source}" 0 ${position} prefix)
    string(REGEX REPLACE "[^{}]" "" braces "${prefix}")
    string(LENGTH "${braces}" brace_length)
    set(depth 0)
    if(brace_length GREATER 0)
        math(EXPR brace_last "${brace_length} - 1")
        foreach(brace_index RANGE 0 ${brace_last})
            string(SUBSTRING "${braces}" ${brace_index} 1 brace)
            if(brace STREQUAL "{")
                math(EXPR depth "${depth} + 1")
            else()
                math(EXPR depth "${depth} - 1")
            endif()
        endforeach()
    endif()
    set(${output} ${depth} PARENT_SCOPE)
endfunction()

function(evidence_cpp_mask_preprocessor_directives_in_sanitized
        source output)
    string(LENGTH "${source}" source_length)
    set(scan 0)
    set(masked "")
    while(scan LESS source_length)
        string(SUBSTRING "${source}" ${scan} -1 tail)
        string(FIND "${tail}" "\n" newline_position)
        if(newline_position EQUAL -1)
            set(line "${tail}")
            set(line_length -1)
        else()
            math(EXPR line_length "${newline_position} + 1")
            string(SUBSTRING "${tail}" 0 ${line_length} line)
        endif()
        if(line MATCHES "^[ \t]*(#|%:)")
            string(REGEX REPLACE "[^\r\n]" " " line "${line}")
        endif()
        string(APPEND masked "${line}")
        if(newline_position EQUAL -1)
            break()
        endif()
        math(EXPR scan "${scan} + ${line_length}")
    endwhile()
    set(${output} "${masked}" PARENT_SCOPE)
endfunction()

function(evidence_cpp_contains_forbidden_renderer_macro source output)
    set(${output} FALSE PARENT_SCOPE)
    string(REGEX MATCHALL
        "(^|\n)[ \t]*(#|%:)[ \t]*define[^\r\n]*"
        macro_definitions "${source}")
    foreach(macro_definition IN LISTS macro_definitions)
        string(REGEX REPLACE
            "^[\r\n \t]*(#|%:)[ \t]*define[ \t]+[A-Za-z_][A-Za-z0-9_]*([ \t]*\\([^\r\n)]*\\))?[ \t]*"
            "" replacement "${macro_definition}")
        set(formed_replacement "${replacement}")
        string(REPLACE "##" "" formed_replacement
            "${formed_replacement}")
        string(REPLACE "%:%:" "" formed_replacement
            "${formed_replacement}")
        string(REGEX REPLACE "[ \t\r\n]" "" formed_replacement
            "${formed_replacement}")
        if(formed_replacement MATCHES
                "(^|[^A-Za-z0-9_])(CombatRenderer|renderer_storage)([^A-Za-z0-9_]|$)"
                OR formed_replacement MATCHES
                "(^|[^A-Za-z0-9_])make_unique<CombatRenderer>([^A-Za-z0-9_]|$)")
            set(${output} TRUE PARENT_SCOPE)
            return()
        endif()
    endforeach()
endfunction()

# The renderer must be constructed only after the fixed-step owner exists, in
# the direct try body. Exact identifier totals make alternate new/reset/direct
# construction paths fail closed without guessing at every C++ spelling.
function(evidence_renderer_allocation_boundary_is_valid source output)
    set(${output} FALSE PARENT_SCOPE)
    string(REGEX REPLACE "[ \t\r\n]+" "" compact "${source}")

    set(owner "std::unique_ptr<CombatRenderer>renderer_storage;")
    set(fixed_step "core::FixedStepRunnerfixed_step;")
    set(allocation
        "renderer_storage=std::make_unique<CombatRenderer>();")
    set(renderer_reference
        "CombatRenderer&renderer=*renderer_storage;")
    set(allocation_anchor
        "${fixed_step}${allocation}${renderer_reference}")
    set(window_owner "HostWindowLifetimewindow{raylib_host_window_backend()};")
    set(window_initialize "window.initialize(config,committed_settings)")
    set(try_token "try{")
    set(standard_catch "catch(conststd::exception&exception){")
    set(unknown_catch "catch(...){")

    foreach(unique_token IN ITEMS
            "${owner}" "${fixed_step}" "${allocation}"
            "${renderer_reference}" "${allocation_anchor}"
            "${window_owner}" "${window_initialize}" "${try_token}"
            "${standard_catch}" "${unknown_catch}")
        evidence_count_literal_occurrences(
            "${compact}" "${unique_token}" token_count)
        if(NOT token_count EQUAL 1)
            return()
        endif()
    endforeach()

    evidence_count_cpp_identifier("${source}" CombatRenderer
        combat_renderer_count)
    evidence_count_cpp_identifier("${source}" renderer_storage
        renderer_storage_count)
    if(NOT combat_renderer_count EQUAL 3
            OR NOT renderer_storage_count EQUAL 7)
        return()
    endif()

    string(FIND "${compact}" "${window_owner}" window_owner_position)
    string(FIND "${compact}" "${owner}" owner_position)
    string(FIND "${compact}" "${try_token}" try_position)
    string(FIND "${compact}" "${window_initialize}"
        window_initialize_position)
    string(FIND "${compact}" "${fixed_step}" fixed_step_position)
    string(FIND "${compact}" "${allocation}" allocation_position)
    string(FIND "${compact}" "${renderer_reference}"
        renderer_reference_position)
    string(FIND "${compact}" "${standard_catch}" standard_catch_position)
    string(FIND "${compact}" "${unknown_catch}" unknown_catch_position)
    if(NOT window_owner_position LESS owner_position
            OR NOT owner_position LESS try_position
            OR NOT try_position LESS window_initialize_position
            OR NOT window_initialize_position LESS fixed_step_position
            OR NOT fixed_step_position LESS allocation_position
            OR NOT allocation_position LESS renderer_reference_position
            OR NOT renderer_reference_position LESS standard_catch_position
            OR NOT standard_catch_position LESS unknown_catch_position)
        return()
    endif()

    evidence_cpp_brace_depth_at("${compact}" ${owner_position} owner_depth)
    evidence_cpp_brace_depth_at("${compact}" ${try_position} try_depth)
    evidence_cpp_brace_depth_at("${compact}" ${window_initialize_position}
        window_initialize_depth)
    evidence_cpp_brace_depth_at("${compact}" ${fixed_step_position}
        fixed_step_depth)
    evidence_cpp_brace_depth_at("${compact}" ${allocation_position}
        allocation_depth)
    evidence_cpp_brace_depth_at("${compact}" ${renderer_reference_position}
        renderer_reference_depth)
    evidence_cpp_brace_depth_at("${compact}" ${standard_catch_position}
        standard_catch_depth)
    evidence_cpp_brace_depth_at("${compact}" ${unknown_catch_position}
        unknown_catch_depth)
    if(NOT owner_depth EQUAL 1 OR NOT try_depth EQUAL 1
            OR NOT window_initialize_depth EQUAL 2
            OR NOT fixed_step_depth EQUAL 2
            OR NOT allocation_depth EQUAL 2
            OR NOT renderer_reference_depth EQUAL 2
            OR NOT standard_catch_depth EQUAL 1
            OR NOT unknown_catch_depth EQUAL 1)
        return()
    endif()
    set(${output} TRUE PARENT_SCOPE)
endfunction()

function(evidence_cpp_prefix_has_exact_namespace_scope_in_sanitized
        source prefix_end expected_namespace output_valid)
    set(${output_valid} FALSE PARENT_SCOPE)
    if(prefix_end LESS_EQUAL 0)
        return()
    endif()
    string(SUBSTRING "${source}" 0 ${prefix_end} prefix_source)
    string(LENGTH "${prefix_source}" prefix_length)
    if(prefix_length EQUAL 0)
        return()
    endif()
    math(EXPR prefix_last "${prefix_length} - 1")
    set(scope_names)
    foreach(character_index RANGE 0 ${prefix_last})
        string(SUBSTRING "${prefix_source}" ${character_index} 1 character)
        if(character STREQUAL "{")
            string(SUBSTRING "${prefix_source}" 0 ${character_index}
                before_open)
            if(before_open MATCHES
                    "(^|[^A-Za-z0-9_])inline[ \t\r\n]+namespace[ \t\r\n]+[A-Za-z_][A-Za-z0-9_]*(::[A-Za-z_][A-Za-z0-9_]*)*[ \t\r\n]*$")
                list(APPEND scope_names "<inline-namespace>")
            elseif(before_open MATCHES
                    "(^|[^A-Za-z0-9_])namespace[ \t\r\n]+([A-Za-z_][A-Za-z0-9_]*(::[A-Za-z_][A-Za-z0-9_]*)*)[ \t\r\n]*$")
                list(APPEND scope_names "${CMAKE_MATCH_2}")
            elseif(before_open MATCHES
                    "(^|[^A-Za-z0-9_])namespace[ \t\r\n]*$")
                list(APPEND scope_names "<anonymous>")
            else()
                list(APPEND scope_names "<non-namespace>")
            endif()
        elseif(character STREQUAL "}")
            list(LENGTH scope_names scope_depth)
            if(scope_depth EQUAL 0)
                return()
            endif()
            list(POP_BACK scope_names)
        endif()
    endforeach()
    list(LENGTH scope_names scope_depth)
    if(expected_namespace STREQUAL "<anonymous>")
        if(scope_depth EQUAL 1)
            list(GET scope_names 0 actual_namespace)
            if(actual_namespace STREQUAL "<anonymous>")
                set(${output_valid} TRUE PARENT_SCOPE)
            endif()
        endif()
        return()
    endif()
    set(actual_namespace_components)
    foreach(scope_name IN LISTS scope_names)
        if(scope_name MATCHES "^<")
            return()
        endif()
        string(REPLACE "::" ";" frame_components "${scope_name}")
        foreach(frame_component IN LISTS frame_components)
            if(NOT frame_component MATCHES
                    "^[A-Za-z_][A-Za-z0-9_]*$")
                return()
            endif()
            list(APPEND actual_namespace_components "${frame_component}")
        endforeach()
    endforeach()
    list(JOIN actual_namespace_components "::" actual_namespace)
    if(NOT actual_namespace STREQUAL expected_namespace)
        return()
    endif()
    set(${output_valid} TRUE PARENT_SCOPE)
endfunction()

function(evidence_try_find_unique_cpp_function_in_namespace_in_sanitized
        source signature expected_namespace output_begin output_open
        output_end output_valid)
    set(${output_begin} -1 PARENT_SCOPE)
    set(${output_open} -1 PARENT_SCOPE)
    set(${output_end} -1 PARENT_SCOPE)
    set(${output_valid} FALSE PARENT_SCOPE)
    string(LENGTH "${source}" source_length)
    set(scan 0)
    set(matching_definition_count 0)
    while(scan LESS source_length)
        string(SUBSTRING "${source}" ${scan} -1 tail)
        string(FIND "${tail}" "${signature}" relative_begin)
        if(relative_begin EQUAL -1)
            break()
        endif()
        math(EXPR candidate_begin "${scan} + ${relative_begin}")
        string(SUBSTRING "${source}" ${candidate_begin} -1 candidate_tail)
        evidence_try_find_cpp_function_bounds_in_sanitized(
            "${candidate_tail}" "${signature}"
            relative_function_begin relative_open relative_end
            candidate_valid)
        if(candidate_valid)
            math(EXPR candidate_open "${candidate_begin} + ${relative_open}")
            math(EXPR candidate_end "${candidate_begin} + ${relative_end}")
            evidence_cpp_prefix_has_exact_namespace_scope_in_sanitized(
                "${source}" ${candidate_begin} "${expected_namespace}"
                namespace_valid)
            if(namespace_valid)
                math(EXPR matching_definition_count
                    "${matching_definition_count} + 1")
                set(matching_begin ${candidate_begin})
                set(matching_open ${candidate_open})
                set(matching_end ${candidate_end})
            endif()
        endif()
        math(EXPR scan "${candidate_begin} + 1")
    endwhile()
    if(NOT matching_definition_count EQUAL 1)
        return()
    endif()
    set(${output_begin} ${matching_begin} PARENT_SCOPE)
    set(${output_open} ${matching_open} PARENT_SCOPE)
    set(${output_end} ${matching_end} PARENT_SCOPE)
    set(${output_valid} TRUE PARENT_SCOPE)
endfunction()

function(evidence_window_lifecycle_source_surface_is_valid
        active_surface lexical_surface source_role output)
    set(expected_SetConfigFlags 0)
    set(expected_InitWindow 0)
    set(expected_IsWindowReady 0)
    set(expected_CloseWindow 0)
    set(expected_WindowShouldClose 0)
    set(expected_lexical_SetConfigFlags 0)
    set(expected_lexical_InitWindow 0)
    set(expected_lexical_IsWindowReady 0)
    set(expected_lexical_CloseWindow 0)
    set(expected_lexical_WindowShouldClose 0)
    set(expected_define_count 0)
    set(expected_undef_count 0)
    if(source_role STREQUAL owner)
        # The owner has one wrapper use plus two unconditional #undef seams:
        # one before raylib.h protects its declarations from project macros,
        # and one after raylib.h protects the wrappers from raylib macros.
        set(expected_SetConfigFlags 3)
        set(expected_InitWindow 3)
        set(expected_IsWindowReady 3)
        set(expected_CloseWindow 3)
        set(expected_lexical_SetConfigFlags 3)
        set(expected_lexical_InitWindow 3)
        set(expected_lexical_IsWindowReady 3)
        set(expected_lexical_CloseWindow 3)
        set(expected_undef_count 8)
    elseif(source_role STREQUAL policy)
        set(expected_lexical_SetConfigFlags 1)
        set(expected_lexical_InitWindow 1)
        set(expected_lexical_IsWindowReady 1)
        set(expected_lexical_CloseWindow 1)
        set(expected_lexical_WindowShouldClose 1)
        set(expected_define_count 5)
    elseif(source_role MATCHES "^ready-([0-9]+)$")
        set(expected_IsWindowReady "${CMAKE_MATCH_1}")
        set(expected_lexical_IsWindowReady "${CMAKE_MATCH_1}")
    elseif(source_role STREQUAL should-close-1)
        set(expected_WindowShouldClose 1)
        set(expected_lexical_WindowShouldClose 1)
    elseif(NOT source_role STREQUAL none)
        set(${output} FALSE PARENT_SCOPE)
        return()
    endif()
    foreach(lifecycle_identifier IN ITEMS
            SetConfigFlags InitWindow IsWindowReady CloseWindow
            WindowShouldClose)
        set(expected_count "${expected_${lifecycle_identifier}}")
        evidence_count_cpp_identifier(
            "${active_surface}" "${lifecycle_identifier}" actual_count)
        if(NOT actual_count EQUAL expected_count)
            set(${output} FALSE PARENT_SCOPE)
            return()
        endif()
        set(expected_lexical_count
            "${expected_lexical_${lifecycle_identifier}}")
        evidence_count_cpp_identifier(
            "${lexical_surface}" "${lifecycle_identifier}"
            actual_lexical_count)
        if(NOT actual_lexical_count EQUAL expected_lexical_count)
            set(${output} FALSE PARENT_SCOPE)
            return()
        endif()
    endforeach()

    set(actual_define_count 0)
    set(actual_undef_count 0)
    foreach(lifecycle_identifier IN ITEMS
            SetConfigFlags InitWindow IsWindowReady CloseWindow
            WindowShouldClose)
        string(REGEX MATCHALL
            "(^|\n)[ \t]*(#|%:)[ \t]*define[ \t]+${lifecycle_identifier}([^A-Za-z0-9_]|$)"
            identifier_defines "${lexical_surface}")
        list(LENGTH identifier_defines identifier_define_count)
        math(EXPR actual_define_count
            "${actual_define_count} + ${identifier_define_count}")
        string(REGEX MATCHALL
            "(^|\n)[ \t]*(#|%:)[ \t]*undef[ \t]+${lifecycle_identifier}([^A-Za-z0-9_]|$)"
            identifier_undefs "${lexical_surface}")
        list(LENGTH identifier_undefs identifier_undef_count)
        math(EXPR actual_undef_count
            "${actual_undef_count} + ${identifier_undef_count}")
        if(lexical_surface MATCHES
                "(^|\n)[ \t]*(#|%:)[ \t]*pragma[ \t]+(push_macro|pop_macro)[ \t]*\\([ \t]*\"${lifecycle_identifier}\"")
            set(${output} FALSE PARENT_SCOPE)
            return()
        endif()
    endforeach()
    if(NOT actual_define_count EQUAL expected_define_count
            OR NOT actual_undef_count EQUAL expected_undef_count)
        set(${output} FALSE PARENT_SCOPE)
        return()
    endif()
    set(${output} TRUE PARENT_SCOPE)
endfunction()

function(evidence_window_lifecycle_owner_surface_is_valid
        active_surface lexical_surface is_owner output)
    if(is_owner)
        set(source_role owner)
    else()
        set(source_role none)
    endif()
    evidence_window_lifecycle_source_surface_is_valid(
        "${active_surface}" "${lexical_surface}" "${source_role}"
        source_surface_valid)
    set(${output} ${source_surface_valid} PARENT_SCOPE)
endfunction()

function(evidence_raylib_lifecycle_source_role
        source_path repo_root output)
    file(TO_CMAKE_PATH "${repo_root}" normalized_root)
    cmake_path(ABSOLUTE_PATH normalized_root NORMALIZE)
    file(TO_CMAKE_PATH "${source_path}" normalized_path)
    cmake_path(ABSOLUTE_PATH normalized_path
        BASE_DIRECTORY "${normalized_root}" NORMALIZE)
    file(RELATIVE_PATH repo_relative_path
        "${normalized_root}" "${normalized_path}")
    file(TO_CMAKE_PATH "${repo_relative_path}" repo_relative_path)
    if(repo_relative_path STREQUAL
            "src/platform/raylib/host_window_lifetime.cpp")
        set(source_role owner)
    elseif(repo_relative_path STREQUAL
            "src/platform/raylib/raylib_lifecycle_poison.hpp")
        set(source_role policy)
    elseif(repo_relative_path STREQUAL
            "src/platform/raylib/combat_renderer.cpp")
        set(source_role ready-1)
    elseif(repo_relative_path STREQUAL
            "src/platform/raylib/death_overlay_renderer.cpp")
        set(source_role ready-2)
    elseif(repo_relative_path STREQUAL
            "src/platform/raylib/hud_renderer.cpp")
        set(source_role ready-4)
    elseif(repo_relative_path STREQUAL
            "src/platform/raylib/pause_menu_renderer.cpp")
        set(source_role ready-1)
    elseif(repo_relative_path STREQUAL
            "src/platform/raylib/window_settings.cpp")
        set(source_role ready-2)
    elseif(repo_relative_path STREQUAL
            "src/platform/raylib/raylib_host.cpp")
        set(source_role should-close-1)
    else()
        set(source_role none)
    endif()
    set(${output} "${source_role}" PARENT_SCOPE)
endfunction()

function(evidence_window_lifetime_boundary_is_valid
        host_direct owner_active owner_lexical output)
    string(REGEX REPLACE "[ \t\r\n]+" "" owner_lexical_compact
        "${owner_lexical}")
    set(wrapper_seam
        "#include\"host_window_lifetime.hpp\"#include\"raylib_host.hpp\"#include\"window_settings.hpp\"#undefSetConfigFlags#undefInitWindow#undefIsWindowReady#undefCloseWindow#include<raylib.h>#undefSetConfigFlags#undefInitWindow#undefIsWindowReady#undefCloseWindownamespace{voidset_config_flags_noexcept(unsignedintflags)noexcept{SetConfigFlags(flags);}voidinit_window_noexcept(intwidth,intheight,constchar*title)noexcept{InitWindow(width,height,title);}boolis_window_ready_noexcept()noexcept{returnIsWindowReady();}voidclose_window_noexcept()noexcept{CloseWindow();}}")
    string(FIND "${owner_lexical_compact}" "${wrapper_seam}"
        wrapper_seam_position)
    evidence_count_literal_occurrences("${owner_lexical_compact}"
        "#include<raylib.h>" raylib_include_count)
    foreach(lifecycle_identifier IN ITEMS
            SetConfigFlags InitWindow IsWindowReady CloseWindow)
        evidence_count_literal_occurrences("${owner_lexical_compact}"
            "#undef${lifecycle_identifier}" undef_count)
        if(NOT undef_count EQUAL 2)
            set(${output} FALSE PARENT_SCOPE)
            return()
        endif()
    endforeach()
    if(NOT wrapper_seam_position EQUAL 0 OR NOT raylib_include_count EQUAL 1)
        set(${output} FALSE PARENT_SCOPE)
        return()
    endif()

    evidence_cpp_mask_preprocessor_directives_in_sanitized(
        "${owner_active}" owner_scope_surface)
    evidence_cpp_normalize_token_whitespace(
        "${owner_scope_surface}" owner_token_surface)
    evidence_try_find_unique_cpp_function_in_namespace_in_sanitized(
        "${owner_token_surface}" "bool HostWindowLifetime::initialize("
        "arpg::platform"
        initialize_begin initialize_open initialize_end initialize_valid)
    if(NOT initialize_valid)
        set(${output} FALSE PARENT_SCOPE)
        return()
    endif()
    math(EXPR initialize_length
        "${initialize_end} - ${initialize_begin} + 1")
    string(SUBSTRING "${owner_token_surface}" ${initialize_begin}
        ${initialize_length} initialize_function)
    evidence_cpp_contains_local_type_keyword_in_sanitized(
        "${initialize_function}" initialize_has_local_type)
    if(initialize_has_local_type)
        set(${output} FALSE PARENT_SCOPE)
        return()
    endif()
    evidence_cpp_direct_execution_surface_in_sanitized(
        "${initialize_function}" initialize_direct)

    evidence_try_find_unique_cpp_function_in_namespace_in_sanitized(
        "${owner_token_surface}" "HostWindowBackend raylib_host_window_backend("
        "arpg::platform"
        backend_begin backend_open backend_end backend_valid)
    if(NOT backend_valid)
        set(${output} FALSE PARENT_SCOPE)
        return()
    endif()
    math(EXPR backend_length "${backend_end} - ${backend_begin} + 1")
    string(SUBSTRING "${owner_token_surface}" ${backend_begin} ${backend_length}
        backend_function)
    evidence_cpp_direct_execution_surface_in_sanitized(
        "${backend_function}" backend_direct)

    string(REGEX REPLACE "[ \t\r\n]+" "" host_compact "${host_direct}")
    string(REGEX REPLACE "[ \t\r\n]+" "" initialize_compact
        "${initialize_direct}")
    string(REGEX REPLACE "[ \t\r\n]+" "" backend_compact
        "${backend_direct}")

    set(host_initialize_call
        "window.initialize(config,committed_settings)")
    string(LENGTH "${host_compact}" before_length)
    string(REPLACE "${host_initialize_call}" "" without_initialize
        "${host_compact}")
    string(LENGTH "${without_initialize}" after_length)
    string(LENGTH "${host_initialize_call}" initialize_call_length)
    math(EXPR host_initialize_count
        "(${before_length} - ${after_length}) / ${initialize_call_length}")
    string(FIND "${host_compact}"
        "if(!${host_initialize_call})" host_initialize_guard)
    if(NOT host_initialize_count EQUAL 1 OR host_initialize_guard EQUAL -1)
        set(${output} FALSE PARENT_SCOPE)
        return()
    endif()
    foreach(forbidden_host_call IN ITEMS
            "SetConfigFlags(" "InitWindow(" "IsWindowReady(" "CloseWindow(")
        string(FIND "${host_direct}" "${forbidden_host_call}"
            forbidden_host_position)
        if(NOT forbidden_host_position EQUAL -1)
            set(${output} FALSE PARENT_SCOPE)
            return()
        endif()
    endforeach()

    set(expected_initialize
        "boolHostWindowLifetime::initialize(constRaylibHostConfig&config,constsettings::SettingsData&settings)noexcept{if(!backend_.set_config_flags||!backend_.init_window||!backend_.is_window_ready||!backend_.close_window){ready_=false;returnfalse;}backend_.set_config_flags(initial_window_flags(settings));backend_.init_window(config.window_width,config.window_height,config.window_title);ready_=backend_.is_window_ready();returnready_;}")
    set(expected_backend
        "HostWindowBackendraylib_host_window_backend()noexcept{return{&set_config_flags_noexcept,&init_window_noexcept,&is_window_ready_noexcept,&close_window_noexcept};}")
    if(NOT initialize_compact STREQUAL expected_initialize
            OR NOT backend_compact STREQUAL expected_backend)
        set(${output} FALSE PARENT_SCOPE)
        return()
    endif()
    set(wrapper_signature_set_config
        "void set_config_flags_noexcept(")
    set(wrapper_signature_init
        "void init_window_noexcept(")
    set(wrapper_signature_ready
        "bool is_window_ready_noexcept(")
    set(wrapper_signature_close
        "void close_window_noexcept(")
    set(wrapper_expected_set_config
        "voidset_config_flags_noexcept(unsignedintflags)noexcept{SetConfigFlags(flags);}")
    set(wrapper_expected_init
        "voidinit_window_noexcept(intwidth,intheight,constchar*title)noexcept{InitWindow(width,height,title);}")
    set(wrapper_expected_ready
        "boolis_window_ready_noexcept()noexcept{returnIsWindowReady();}")
    set(wrapper_expected_close
        "voidclose_window_noexcept()noexcept{CloseWindow();}")
    foreach(wrapper_id IN ITEMS set_config init ready close)
        set(signature_variable "wrapper_signature_${wrapper_id}")
        set(expected_variable "wrapper_expected_${wrapper_id}")
        evidence_try_find_unique_cpp_function_in_namespace_in_sanitized(
            "${owner_token_surface}" "${${signature_variable}}" "<anonymous>"
            wrapper_begin wrapper_open wrapper_end wrapper_valid)
        if(NOT wrapper_valid)
            set(${output} FALSE PARENT_SCOPE)
            return()
        endif()
        math(EXPR wrapper_length "${wrapper_end} - ${wrapper_begin} + 1")
        string(SUBSTRING "${owner_token_surface}" ${wrapper_begin}
            ${wrapper_length} wrapper_function)
        string(REGEX REPLACE "[ \t\r\n]+" "" wrapper_compact
            "${wrapper_function}")
        if(NOT wrapper_compact STREQUAL "${${expected_variable}}")
            set(${output} FALSE PARENT_SCOPE)
            return()
        endif()
    endforeach()
    evidence_window_lifecycle_owner_surface_is_valid(
        "${owner_active}" "${owner_lexical}" TRUE owner_surface_valid)
    if(NOT owner_surface_valid)
        set(${output} FALSE PARENT_SCOPE)
        return()
    endif()
    set(${output} TRUE PARENT_SCOPE)
endfunction()
