# Shared source scanner for evidence guards. Non-code characters become spaces
# while line endings and source length remain unchanged, so brace offsets stay valid.
function(evidence_is_cpp_splice source index output)
    string(ASCII 10 newline)
    string(ASCII 13 carriage_return)
    string(ASCII 92 backslash)
    string(LENGTH "${source}" source_length)
    if(index GREATER_EQUAL source_length)
        set(${output} FALSE PARENT_SCOPE)
        return()
    endif()
    string(SUBSTRING "${source}" ${index} 1 character)
    if(NOT character STREQUAL "${backslash}")
        set(${output} FALSE PARENT_SCOPE)
        return()
    endif()
    math(EXPR next_index "${index} + 1")
    if(next_index GREATER_EQUAL source_length)
        set(${output} FALSE PARENT_SCOPE)
        return()
    endif()
    string(SUBSTRING "${source}" ${next_index} 1 next_character)
    if(next_character STREQUAL "${newline}")
        set(${output} TRUE PARENT_SCOPE)
        return()
    endif()
    math(EXPR after_next_index "${index} + 2")
    if(next_character STREQUAL "${carriage_return}"
            AND after_next_index LESS source_length)
        string(SUBSTRING "${source}" ${after_next_index} 1 after_next_character)
        if(after_next_character STREQUAL "${newline}")
            set(${output} TRUE PARENT_SCOPE)
            return()
        endif()
    endif()
    set(${output} FALSE PARENT_SCOPE)
endfunction()

function(evidence_cpp_logical_next_character source start output_character output_found)
    string(ASCII 10 newline)
    string(ASCII 13 carriage_return)
    string(LENGTH "${source}" source_length)
    set(probe ${start})
    while(probe LESS source_length)
        evidence_is_cpp_splice("${source}" ${probe} is_splice)
        if(is_splice)
            math(EXPR newline_index "${probe} + 1")
            string(SUBSTRING "${source}" ${newline_index} 1 splice_newline)
            if(splice_newline STREQUAL "${carriage_return}")
                math(EXPR probe "${probe} + 3")
            else()
                math(EXPR probe "${probe} + 2")
            endif()
        else()
            string(SUBSTRING "${source}" ${probe} 1 logical_character)
            set(${output_character} "${logical_character}" PARENT_SCOPE)
            set(${output_found} TRUE PARENT_SCOPE)
            return()
        endif()
    endwhile()
    set(${output_character} "" PARENT_SCOPE)
    set(${output_found} FALSE PARENT_SCOPE)
endfunction()

function(evidence_sanitize_cpp_for_scan source output)
    string(ASCII 10 newline)
    string(ASCII 13 carriage_return)
    string(ASCII 34 double_quote)
    string(ASCII 39 single_quote)
    string(ASCII 92 backslash)
    string(LENGTH "${source}" source_length)
    if(source_length EQUAL 0)
        set(${output} "" PARENT_SCOPE)
        return()
    endif()

    math(EXPR source_last "${source_length} - 1")
    set(sanitized "")
    set(scan_state code)
    set(escaped FALSE)
    foreach(character_index RANGE 0 ${source_last})
        string(SUBSTRING "${source}" ${character_index} 1 character)
        set(next_character "")
        set(next_found FALSE)
        if(character_index LESS source_last)
            math(EXPR next_character_index "${character_index} + 1")
            evidence_cpp_logical_next_character("${source}" ${next_character_index}
                next_character next_found)
        endif()

        if(scan_state STREQUAL "code")
            if(next_found AND character STREQUAL "/" AND next_character STREQUAL "/")
                set(scan_state line_comment)
                string(APPEND sanitized " ")
            elseif(next_found AND character STREQUAL "/" AND next_character STREQUAL "*")
                set(scan_state block_comment)
                string(APPEND sanitized " ")
            elseif(character STREQUAL "${double_quote}")
                set(scan_state string_literal)
                set(escaped FALSE)
                string(APPEND sanitized " ")
            elseif(character STREQUAL "${single_quote}")
                set(scan_state character_literal)
                set(escaped FALSE)
                string(APPEND sanitized " ")
            else()
                string(APPEND sanitized "${character}")
            endif()
        elseif(scan_state STREQUAL "line_comment")
            evidence_is_cpp_splice("${source}" ${character_index} is_splice)
            if(character STREQUAL "${backslash}" AND is_splice)
                set(scan_state line_comment_splice)
                string(APPEND sanitized " ")
            elseif(character STREQUAL "${newline}" OR character STREQUAL "${carriage_return}")
                set(scan_state code)
                string(APPEND sanitized "${character}")
            else()
                string(APPEND sanitized " ")
            endif()
        elseif(scan_state STREQUAL "line_comment_splice")
            if(character STREQUAL "${newline}")
                set(scan_state line_comment)
                string(APPEND sanitized "${character}")
            elseif(character STREQUAL "${carriage_return}")
                string(APPEND sanitized "${character}")
            else()
                message(FATAL_ERROR "Evidence scanner expected a line splice terminator")
            endif()
        elseif(scan_state STREQUAL "block_comment")
            if(character STREQUAL "*" AND next_found AND next_character STREQUAL "/")
                set(scan_state block_comment_close_pending)
            endif()
            if(character STREQUAL "${newline}" OR character STREQUAL "${carriage_return}")
                string(APPEND sanitized "${character}")
            else()
                string(APPEND sanitized " ")
            endif()
        elseif(scan_state STREQUAL "block_comment_close_pending")
            evidence_is_cpp_splice("${source}" ${character_index} is_splice)
            if(character STREQUAL "${backslash}" AND is_splice)
                set(scan_state block_comment_close_splice)
            elseif(character STREQUAL "/")
                set(scan_state code)
            endif()
            if(character STREQUAL "${newline}" OR character STREQUAL "${carriage_return}")
                string(APPEND sanitized "${character}")
            else()
                string(APPEND sanitized " ")
            endif()
        elseif(scan_state STREQUAL "block_comment_close_splice")
            if(character STREQUAL "${newline}")
                set(scan_state block_comment_close_pending)
                string(APPEND sanitized "${character}")
            elseif(character STREQUAL "${carriage_return}")
                string(APPEND sanitized "${character}")
            else()
                message(FATAL_ERROR "Evidence scanner expected a block-comment splice terminator")
            endif()
        elseif(scan_state STREQUAL "string_literal"
                OR scan_state STREQUAL "character_literal")
            evidence_is_cpp_splice("${source}" ${character_index} is_splice)
            if(character STREQUAL "${backslash}" AND is_splice)
                set(splice_return_state "${scan_state}")
                set(scan_state literal_splice)
            elseif(escaped)
                set(escaped FALSE)
            elseif(character STREQUAL "${backslash}")
                set(escaped TRUE)
            elseif((scan_state STREQUAL "string_literal" AND character STREQUAL "${double_quote}")
                    OR (scan_state STREQUAL "character_literal" AND character STREQUAL "${single_quote}"))
                set(scan_state code)
            endif()
            if(character STREQUAL "${newline}" OR character STREQUAL "${carriage_return}")
                string(APPEND sanitized "${character}")
            else()
                string(APPEND sanitized " ")
            endif()
        elseif(scan_state STREQUAL "literal_splice")
            if(character STREQUAL "${newline}")
                set(scan_state "${splice_return_state}")
                string(APPEND sanitized "${character}")
            elseif(character STREQUAL "${carriage_return}")
                string(APPEND sanitized "${character}")
            else()
                message(FATAL_ERROR "Evidence scanner expected a literal splice terminator")
            endif()
        endif()
    endforeach()
    set(${output} "${sanitized}" PARENT_SCOPE)
endfunction()

function(evidence_find_cpp_function_bounds_in_sanitized sanitized_source signature output_begin output_open output_end)
    string(FIND "${sanitized_source}" "${signature}" function_begin)
    if(function_begin EQUAL -1)
        message(FATAL_ERROR "Evidence validation function is missing: ${signature}")
    endif()
    string(SUBSTRING "${sanitized_source}" ${function_begin} -1 function_tail)
    string(FIND "${function_tail}" "{" brace_relative)
    if(brace_relative EQUAL -1)
        message(FATAL_ERROR "Evidence validation function has no opening brace: ${signature}")
    endif()
    math(EXPR brace_open "${function_begin} + ${brace_relative}")
    string(LENGTH "${sanitized_source}" source_length)
    math(EXPR source_last "${source_length} - 1")
    set(brace_depth 0)
    set(function_end -1)
    foreach(character_index RANGE ${brace_open} ${source_last})
        string(SUBSTRING "${sanitized_source}" ${character_index} 1 character)
        if(character STREQUAL "{")
            math(EXPR brace_depth "${brace_depth} + 1")
        elseif(character STREQUAL "}")
            math(EXPR brace_depth "${brace_depth} - 1")
            if(brace_depth EQUAL 0)
                set(function_end ${character_index})
                break()
            endif()
        endif()
    endforeach()
    if(function_end EQUAL -1)
        message(FATAL_ERROR "Evidence validation function has unbalanced braces: ${signature}")
    endif()
    set(${output_begin} ${function_begin} PARENT_SCOPE)
    set(${output_open} ${brace_open} PARENT_SCOPE)
    set(${output_end} ${function_end} PARENT_SCOPE)
endfunction()

function(evidence_find_cpp_function_bounds source signature output_begin output_open output_end)
    evidence_sanitize_cpp_for_scan("${source}" sanitized_source)
    evidence_find_cpp_function_bounds_in_sanitized("${sanitized_source}" "${signature}"
        function_begin function_open function_end)
    set(${output_begin} ${function_begin} PARENT_SCOPE)
    set(${output_open} ${function_open} PARENT_SCOPE)
    set(${output_end} ${function_end} PARENT_SCOPE)
endfunction()

function(evidence_extract_cpp_function_block source signature output)
    evidence_sanitize_cpp_for_scan("${source}" sanitized_source)
    evidence_find_cpp_function_bounds_in_sanitized("${sanitized_source}" "${signature}"
        function_begin function_open function_end)
    math(EXPR function_length "${function_end} - ${function_begin} + 1")
    string(SUBSTRING "${sanitized_source}" ${function_begin} ${function_length}
        function_block)
    set(${output} "${function_block}" PARENT_SCOPE)
endfunction()

# Finds a token only when it begins in C++ code. This is intentionally a
# lexical state walk rather than regex comment stripping. It visits delimiters
# instead of every source character so a caller can prove a raw crop starts in
# code without paying for a full sanitized copy of a large translation unit.
function(evidence_find_cpp_from_offset source start token output)
    string(SUBSTRING "${source}" ${start} -1 source_tail)
    string(FIND "${source_tail}" "${token}" relative_position)
    if(relative_position EQUAL -1)
        set(${output} -1 PARENT_SCOPE)
    else()
        math(EXPR absolute_position "${start} + ${relative_position}")
        set(${output} ${absolute_position} PARENT_SCOPE)
    endif()
endfunction()

function(evidence_find_cpp_code_token source token output)
    string(ASCII 10 newline)
    string(ASCII 13 carriage_return)
    string(ASCII 34 double_quote)
    string(ASCII 39 single_quote)
    string(ASCII 92 backslash)
    string(LENGTH "${source}" source_length)
    set(scan 0)
    set(scan_state code)
    set(token_position -1)
    while(scan LESS source_length)
        evidence_find_cpp_from_offset("${source}" ${scan} "${token}" candidate)
        if(scan_state STREQUAL "code")
            set(next_marker -1)
            foreach(marker IN ITEMS "/" "${double_quote}" "${single_quote}")
                evidence_find_cpp_from_offset("${source}" ${scan} "${marker}" marker_position)
                if(NOT marker_position EQUAL -1
                        AND (next_marker EQUAL -1 OR marker_position LESS next_marker))
                    set(next_marker ${marker_position})
                endif()
            endforeach()
            if(NOT candidate EQUAL -1
                    AND (next_marker EQUAL -1 OR candidate LESS next_marker))
                set(token_position ${candidate})
                break()
            endif()
            if(next_marker EQUAL -1)
                break()
            endif()
            string(SUBSTRING "${source}" ${next_marker} 1 marker_character)
            if(marker_character STREQUAL "/")
                math(EXPR after_slash "${next_marker} + 1")
                evidence_cpp_logical_next_character("${source}" ${after_slash}
                    next_character next_found)
                if(next_found AND next_character STREQUAL "/")
                    set(scan_state line_comment)
                elseif(next_found AND next_character STREQUAL "*")
                    set(scan_state block_comment)
                endif()
            elseif(marker_character STREQUAL "${double_quote}")
                set(scan_state string_literal)
            else()
                set(scan_state character_literal)
            endif()
            math(EXPR scan "${next_marker} + 1")
        elseif(scan_state STREQUAL "line_comment")
            set(next_marker -1)
            foreach(marker IN ITEMS "${backslash}" "${newline}" "${carriage_return}")
                evidence_find_cpp_from_offset("${source}" ${scan} "${marker}" marker_position)
                if(NOT marker_position EQUAL -1
                        AND (next_marker EQUAL -1 OR marker_position LESS next_marker))
                    set(next_marker ${marker_position})
                endif()
            endforeach()
            if(next_marker EQUAL -1)
                break()
            endif()
            string(SUBSTRING "${source}" ${next_marker} 1 marker_character)
            if(marker_character STREQUAL "${backslash}")
                evidence_is_cpp_splice("${source}" ${next_marker} is_splice)
                if(is_splice)
                    math(EXPR after_backslash "${next_marker} + 1")
                    string(SUBSTRING "${source}" ${after_backslash} 1 splice_character)
                    if(splice_character STREQUAL "${carriage_return}")
                        math(EXPR scan "${next_marker} + 3")
                    else()
                        math(EXPR scan "${next_marker} + 2")
                    endif()
                    continue()
                endif()
            elseif(marker_character STREQUAL "${newline}"
                    OR marker_character STREQUAL "${carriage_return}")
                set(scan_state code)
            endif()
            math(EXPR scan "${next_marker} + 1")
        elseif(scan_state STREQUAL "block_comment")
            evidence_find_cpp_from_offset("${source}" ${scan} "*" next_marker)
            if(next_marker EQUAL -1)
                break()
            endif()
            math(EXPR after_star "${next_marker} + 1")
            evidence_cpp_logical_next_character("${source}" ${after_star}
                next_character next_found)
            if(next_found AND next_character STREQUAL "/")
                set(scan_state code)
            endif()
            math(EXPR scan "${next_marker} + 1")
        else()
            if(scan_state STREQUAL "string_literal")
                set(quote_character "${double_quote}")
            else()
                set(quote_character "${single_quote}")
            endif()
            set(next_marker -1)
            foreach(marker IN ITEMS "${backslash}" "${quote_character}")
                evidence_find_cpp_from_offset("${source}" ${scan} "${marker}" marker_position)
                if(NOT marker_position EQUAL -1
                        AND (next_marker EQUAL -1 OR marker_position LESS next_marker))
                    set(next_marker ${marker_position})
                endif()
            endforeach()
            if(next_marker EQUAL -1)
                break()
            endif()
            string(SUBSTRING "${source}" ${next_marker} 1 marker_character)
            if(marker_character STREQUAL "${backslash}")
                evidence_is_cpp_splice("${source}" ${next_marker} is_splice)
                if(is_splice)
                    math(EXPR after_backslash "${next_marker} + 1")
                    string(SUBSTRING "${source}" ${after_backslash} 1 splice_character)
                    if(splice_character STREQUAL "${carriage_return}")
                        math(EXPR scan "${next_marker} + 3")
                    else()
                        math(EXPR scan "${next_marker} + 2")
                    endif()
                else()
                    math(EXPR scan "${next_marker} + 2")
                endif()
            else()
                set(scan_state code)
                math(EXPR scan "${next_marker} + 1")
            endif()
        endif()
    endwhile()
    set(${output} ${token_position} PARENT_SCOPE)
endfunction()
