foreach(required FIXTURE_SOURCE FORMAL_SOURCE CAPTURE_SCRIPT HOST_HEADER HOST_SOURCE)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Stage 11 evidence guard missing ${required}")
    endif()
endforeach()
file(READ "${FIXTURE_SOURCE}" fixture_source)
file(READ "${FORMAL_SOURCE}" formal_source)
file(READ "${CAPTURE_SCRIPT}" capture_script)
file(READ "${HOST_HEADER}" host_header)
file(READ "${HOST_SOURCE}" host_source)
set(all_evidence "${fixture_source}\n${formal_source}\n${host_header}\n${host_source}")

foreach(forbidden "DungeonSessionTestAccess" "CombatWorldTestAccess"
        "force_defeat" "stable_state_" "phase_[ \t]*="
        "death_checkpoint[ \t]*=" "pending_save_[ \t]*=")
    if(all_evidence MATCHES "${forbidden}")
        message(FATAL_ERROR "Forbidden Stage 11 evidence injection: ${forbidden}")
    endif()
endforeach()

foreach(required_fixture "SaveStore" "session.tick" "pending_save_view"
        "request_death_continue" "store.commit" "store.load")
    if(NOT fixture_source MATCHES "${required_fixture}")
        message(FATAL_ERROR "Fixture lacks production API: ${required_fixture}")
    endif()
endforeach()
foreach(required_host "stage11_validation_input" "queue_action"
        "MovementInput" "runtime.fixed_tick" "request_death_continue")
    if(NOT host_source MATCHES "${required_host}")
        message(FATAL_ERROR "Formal host lacks production input/save path: ${required_host}")
    endif()
endforeach()
if(NOT formal_source MATCHES "run_raylib_host"
        OR NOT formal_source MATCHES "SaveStore"
        OR NOT formal_source MATCHES "formal-path-summary.txt")
    message(FATAL_ERROR "Formal Stage 11 executable lacks real host/save/summary evidence")
endif()
foreach(required_script "LastWriteTimeUtc" "System.Drawing" "GetPixel"
        "nonBackground" "Get-PanelHash" "formal-path-summary.txt")
    if(NOT capture_script MATCHES "${required_script}")
        message(FATAL_ERROR "Capture validator lacks ${required_script}")
    endif()
endforeach()

string(ASCII 9 tab)
string(ASCII 10 lf)
string(ASCII 13 cr)
string(REPLACE " " "" compact "${host_source}")
string(REPLACE "${tab}" "" compact "${compact}")
string(REPLACE "${lf}" "" compact "${compact}")
string(REPLACE "${cr}" "" compact "${compact}")
set(helper "voidpresent_frame_and_maybe_capture(constchar*path)noexcept{EndDrawing();if(path==nullptr)return;Imageimage=LoadImageFromScreen();if(image.data==nullptr)return;static_cast<void>(ExportImage(image,path));UnloadImage(image);}")
string(FIND "${compact}" "${helper}" helper_index)
string(REGEX MATCHALL "EndDrawing\\(\\)" ends "${compact}")
string(REGEX MATCHALL "LoadImageFromScreen\\(\\)" loads "${compact}")
string(REGEX MATCHALL "ExportImage\\(" exports "${compact}")
list(LENGTH ends end_count)
list(LENGTH loads load_count)
list(LENGTH exports export_count)
if(helper_index EQUAL -1 OR NOT end_count EQUAL 1
        OR NOT load_count EQUAL 1 OR NOT export_count EQUAL 1)
    message(FATAL_ERROR "Capture must occur once after EndDrawing (helper=${helper_index} end=${end_count} load=${load_count} export=${export_count})")
endif()
message(STATUS "Stage 11 production evidence guard passed")
