# Counts an exact, unquoted source argument only while parsing the raw lines of
# add_library(arpg_raylib ...) or target_sources(arpg_raylib ...).  In
# particular, comments are removed before semicolons can be interpreted as
# list separators.
function(arpg_cmake_code_line_and_paren_delta LINE OUT_CODE OUT_DELTA)
    string(LENGTH "${LINE}" _length)
    set(_scan 0)
    set(_quoted FALSE)
    set(_escaped FALSE)
    set(_code "")
    set(_delta 0)
    while(_scan LESS _length)
        string(SUBSTRING "${LINE}" ${_scan} 1 _character)
        if(_quoted)
            string(APPEND _code "${_character}")
            if(_escaped)
                set(_escaped FALSE)
            elseif(_character STREQUAL "\\")
                set(_escaped TRUE)
            elseif(_character STREQUAL "\"")
                set(_quoted FALSE)
            endif()
        else()
            if(_character STREQUAL "#")
                break()
            endif()
            string(APPEND _code "${_character}")
            if(_character STREQUAL "\"")
                set(_quoted TRUE)
            elseif(_character STREQUAL "(")
                math(EXPR _delta "${_delta} + 1")
            elseif(_character STREQUAL ")")
                math(EXPR _delta "${_delta} - 1")
            endif()
        endif()
        math(EXPR _scan "${_scan} + 1")
    endwhile()
    set(${OUT_CODE} "${_code}" PARENT_SCOPE)
    set(${OUT_DELTA} ${_delta} PARENT_SCOPE)
endfunction()

function(arpg_cmake_count_arpg_raylib_source CMAKE_TEXT SOURCE OUT_COUNT)
    string(REPLACE "\r\n" "\n" _text "${CMAKE_TEXT}")
    string(REPLACE "\r" "\n" _text "${_text}")
    string(LENGTH "${_text}" _length)
    set(_scan 0)
    set(_inside FALSE)
    set(_paren_depth 0)
    set(_count 0)
    while(_scan LESS_EQUAL _length)
        if(_scan EQUAL _length)
            set(_line "")
            set(_next -1)
        else()
            string(SUBSTRING "${_text}" ${_scan} -1 _tail)
            string(FIND "${_tail}" "\n" _relative_newline)
            if(_relative_newline EQUAL -1)
                set(_line "${_tail}")
                set(_next -1)
            else()
                string(SUBSTRING "${_tail}" 0 ${_relative_newline} _line)
                math(EXPR _next "${_scan} + ${_relative_newline}")
            endif()
        endif()
        arpg_cmake_code_line_and_paren_delta("${_line}" _code _delta)
        if(NOT _inside)
            if(_code MATCHES
                    "^[ \t]*(add_library|target_sources)[ \t]*[(][ \t]*arpg_raylib([ \t]|[)])")
                set(_inside TRUE)
                set(_paren_depth ${_delta})
            endif()
        else()
            if(_code MATCHES "^[ \t]*${SOURCE}[ \t]*$")
                math(EXPR _count "${_count} + 1")
            endif()
            math(EXPR _paren_depth "${_paren_depth} + ${_delta}")
            if(_paren_depth LESS_EQUAL 0)
                set(_inside FALSE)
            endif()
        endif()
        if(_next EQUAL -1)
            break()
        endif()
        math(EXPR _scan "${_next} + 1")
    endwhile()
    set(${OUT_COUNT} ${_count} PARENT_SCOPE)
endfunction()
