# Counts an exact, unquoted source argument only while parsing the code-state
# lines of add_library(arpg_raylib ...) or target_sources(arpg_raylib ...).
# CMake bracket comments and bracket arguments are lexical regions: their
# contents never contribute source names, comments, semicolons, or parentheses.
function(arpg_cmake_bracket_opener SOURCE POSITION OUT_FOUND OUT_CLOSE OUT_AFTER)
    string(LENGTH "${SOURCE}" _length)
    if(POSITION GREATER_EQUAL _length)
        set(${OUT_FOUND} FALSE PARENT_SCOPE)
        return()
    endif()
    string(SUBSTRING "${SOURCE}" ${POSITION} 1 _open)
    if(NOT _open STREQUAL "[")
        set(${OUT_FOUND} FALSE PARENT_SCOPE)
        return()
    endif()
    math(EXPR _scan "${POSITION} + 1")
    set(_equals "")
    while(_scan LESS _length)
        string(SUBSTRING "${SOURCE}" ${_scan} 1 _character)
        if(NOT _character STREQUAL "=")
            break()
        endif()
        string(APPEND _equals "=")
        math(EXPR _scan "${_scan} + 1")
    endwhile()
    if(_scan LESS _length)
        string(SUBSTRING "${SOURCE}" ${_scan} 1 _close_open)
        if(_close_open STREQUAL "[")
            math(EXPR _after "${_scan} + 1")
            set(${OUT_FOUND} TRUE PARENT_SCOPE)
            set(${OUT_CLOSE} "]${_equals}]" PARENT_SCOPE)
            set(${OUT_AFTER} ${_after} PARENT_SCOPE)
            return()
        endif()
    endif()
    set(${OUT_FOUND} FALSE PARENT_SCOPE)
endfunction()

function(arpg_cmake_append_masked COUNT OUT)
    set(_masked "")
    if(COUNT GREATER 0)
        math(EXPR _last "${COUNT} - 1")
        foreach(_index RANGE 0 ${_last})
            string(APPEND _masked " ")
        endforeach()
    endif()
    set(${OUT} "${_masked}" PARENT_SCOPE)
endfunction()

function(arpg_cmake_code_surface CMAKE_TEXT OUT_SURFACE)
    string(REPLACE "\r\n" "\n" _text "${CMAKE_TEXT}")
    string(REPLACE "\r" "\n" _text "${_text}")
    string(LENGTH "${_text}" _length)
    string(ASCII 10 _newline)
    string(ASCII 34 _double_quote)
    string(ASCII 92 _backslash)
    set(_scan 0)
    set(_state normal)
    set(_escaped FALSE)
    set(_bracket_close "")
    set(_surface "")
    while(_scan LESS _length)
        string(SUBSTRING "${_text}" ${_scan} 1 _character)
        if(_state STREQUAL "normal")
            if(_character STREQUAL "${_double_quote}")
                string(APPEND _surface " ")
                set(_state double_quote)
                set(_escaped FALSE)
                math(EXPR _scan "${_scan} + 1")
                continue()
            endif()
            if(_character STREQUAL "#")
                math(EXPR _after_hash "${_scan} + 1")
                arpg_cmake_bracket_opener("${_text}" ${_after_hash}
                    _bracket_found _bracket_close _after_open)
                if(_bracket_found)
                    math(EXPR _opener_length "${_after_open} - ${_scan}")
                    arpg_cmake_append_masked(${_opener_length} _masked)
                    string(APPEND _surface "${_masked}")
                    set(_state bracket_comment)
                    set(_scan ${_after_open})
                    continue()
                endif()
                string(APPEND _surface " ")
                set(_state line_comment)
                math(EXPR _scan "${_scan} + 1")
                continue()
            endif()
            if(_character STREQUAL "[")
                arpg_cmake_bracket_opener("${_text}" ${_scan}
                    _bracket_found _bracket_close _after_open)
                if(_bracket_found)
                    math(EXPR _opener_length "${_after_open} - ${_scan}")
                    arpg_cmake_append_masked(${_opener_length} _masked)
                    string(APPEND _surface "${_masked}")
                    set(_state bracket_argument)
                    set(_scan ${_after_open})
                    continue()
                endif()
            endif()
            string(APPEND _surface "${_character}")
        elseif(_state STREQUAL "double_quote")
            if(_character STREQUAL "${_newline}")
                string(APPEND _surface "${_newline}")
            else()
                string(APPEND _surface " ")
            endif()
            if(_escaped)
                set(_escaped FALSE)
            elseif(_character STREQUAL "${_backslash}")
                set(_escaped TRUE)
            elseif(_character STREQUAL "${_double_quote}")
                set(_state normal)
            endif()
        elseif(_state STREQUAL "line_comment")
            if(_character STREQUAL "${_newline}")
                string(APPEND _surface "${_newline}")
                set(_state normal)
            else()
                string(APPEND _surface " ")
            endif()
        else()
            string(LENGTH "${_bracket_close}" _close_length)
            string(SUBSTRING "${_text}" ${_scan} ${_close_length} _candidate)
            if(_candidate STREQUAL "${_bracket_close}")
                arpg_cmake_append_masked(${_close_length} _masked)
                string(APPEND _surface "${_masked}")
                math(EXPR _scan "${_scan} + ${_close_length}")
                set(_state normal)
                continue()
            endif()
            if(_character STREQUAL "${_newline}")
                string(APPEND _surface "${_newline}")
            else()
                string(APPEND _surface " ")
            endif()
        endif()
        math(EXPR _scan "${_scan} + 1")
    endwhile()
    set(${OUT_SURFACE} "${_surface}" PARENT_SCOPE)
endfunction()

function(arpg_cmake_code_line_and_paren_delta LINE OUT_DELTA)
    string(REGEX REPLACE "[^()]" "" _parentheses "${LINE}")
    string(LENGTH "${_parentheses}" _length)
    set(_delta 0)
    if(_length GREATER 0)
        math(EXPR _last "${_length} - 1")
        foreach(_index RANGE 0 ${_last})
            string(SUBSTRING "${_parentheses}" ${_index} 1 _character)
            if(_character STREQUAL "(")
                math(EXPR _delta "${_delta} + 1")
            else()
                math(EXPR _delta "${_delta} - 1")
            endif()
        endforeach()
    endif()
    set(${OUT_DELTA} ${_delta} PARENT_SCOPE)
endfunction()

function(arpg_cmake_count_arpg_raylib_source CMAKE_TEXT SOURCE OUT_COUNT)
    arpg_cmake_code_surface("${CMAKE_TEXT}" _surface)
    string(LENGTH "${_surface}" _length)
    set(_scan 0)
    set(_inside FALSE)
    set(_paren_depth 0)
    set(_count 0)
    while(_scan LESS_EQUAL _length)
        if(_scan EQUAL _length)
            set(_line "")
            set(_next -1)
        else()
            string(SUBSTRING "${_surface}" ${_scan} -1 _tail)
            string(FIND "${_tail}" "\n" _relative_newline)
            if(_relative_newline EQUAL -1)
                set(_line "${_tail}")
                set(_next -1)
            else()
                string(SUBSTRING "${_tail}" 0 ${_relative_newline} _line)
                math(EXPR _next "${_scan} + ${_relative_newline}")
            endif()
        endif()
        arpg_cmake_code_line_and_paren_delta("${_line}" _delta)
        if(NOT _inside)
            if(_line MATCHES
                    "^[ \t]*(add_library|target_sources)[ \t]*[(][ \t]*arpg_raylib([ \t]|[)])")
                set(_inside TRUE)
                set(_paren_depth ${_delta})
            endif()
        else()
            if(_line MATCHES "^[ \t]*${SOURCE}[ \t]*$")
                math(EXPR _count "${_count} + 1")
            endif()
            math(EXPR _paren_depth "${_paren_depth} + ${_delta}")
            if(_paren_depth LESS_EQUAL 0)
                set(_inside FALSE)
            endif()
        endif()
        if(_next EQUAL -1)
            break()
        endif()
        math(EXPR _scan "${_next} + 1")
    endwhile()
    set(${OUT_COUNT} ${_count} PARENT_SCOPE)
endfunction()
