function(evidence_host_success_tail_is_canonical
        HOST_FUNCTION OUT_VALID OUT_REASON)
    set(_loop_token "while (!exit_requested) {")
    string(FIND "${HOST_FUNCTION}" "${_loop_token}" _loop_begin)
    if(_loop_begin EQUAL -1)
        set(${OUT_VALID} FALSE PARENT_SCOPE)
        set(${OUT_REASON} "host loop is missing" PARENT_SCOPE)
        return()
    endif()

    math(EXPR _after_loop_token "${_loop_begin} + 1")
    string(SUBSTRING "${HOST_FUNCTION}" ${_after_loop_token} -1
        _loop_remainder)
    string(FIND "${_loop_remainder}" "${_loop_token}" _duplicate_loop)
    if(NOT _duplicate_loop EQUAL -1)
        set(${OUT_VALID} FALSE PARENT_SCOPE)
        set(${OUT_REASON} "host loop is duplicated" PARENT_SCOPE)
        return()
    endif()

    string(SUBSTRING "${HOST_FUNCTION}" ${_loop_begin} -1 _loop_tail)
    string(FIND "${_loop_tail}" "{" _loop_open_relative)
    if(_loop_open_relative EQUAL -1)
        set(${OUT_VALID} FALSE PARENT_SCOPE)
        set(${OUT_REASON} "host loop brace is missing" PARENT_SCOPE)
        return()
    endif()
    math(EXPR _loop_open "${_loop_begin} + ${_loop_open_relative}")
    string(LENGTH "${HOST_FUNCTION}" _host_length)
    math(EXPR _host_last "${_host_length} - 1")
    set(_depth 0)
    set(_loop_end -1)
    foreach(_index RANGE ${_loop_open} ${_host_last})
        string(SUBSTRING "${HOST_FUNCTION}" ${_index} 1 _character)
        if(_character STREQUAL "{")
            math(EXPR _depth "${_depth} + 1")
        elseif(_character STREQUAL "}")
            math(EXPR _depth "${_depth} - 1")
            if(_depth EQUAL 0)
                set(_loop_end ${_index})
                break()
            endif()
        endif()
    endforeach()
    if(_loop_end EQUAL -1)
        set(${OUT_VALID} FALSE PARENT_SCOPE)
        set(${OUT_REASON} "host loop is unbalanced" PARENT_SCOPE)
        return()
    endif()

    math(EXPR _success_tail_begin "${_loop_end} + 1")
    string(SUBSTRING "${HOST_FUNCTION}" ${_success_tail_begin} -1
        _post_loop)
    string(FIND "${_post_loop}" "} catch (" _catch_begin)
    if(_catch_begin EQUAL -1)
        set(${OUT_VALID} FALSE PARENT_SCOPE)
        set(${OUT_REASON} "host catch boundary is missing" PARENT_SCOPE)
        return()
    endif()
    string(SUBSTRING "${_post_loop}" 0 ${_catch_begin} _success_tail)
    string(REGEX REPLACE "[ \t\r\n]+" "" _success_tail_compact
        "${_success_tail}")
    set(_canonical_tail
        "validation_runtime->write_summaries(runtime.clean_shutdown_state(),pause_menu);audio.shutdown();renderer.shutdown_resources();pause_menu_renderer.shutdown();window.close();returnHostExitCode::success;")
    if(NOT _success_tail_compact STREQUAL _canonical_tail)
        set(${OUT_VALID} FALSE PARENT_SCOPE)
        set(${OUT_REASON} "post-loop success tail is not canonical" PARENT_SCOPE)
        return()
    endif()

    string(REGEX REPLACE "[ \t\r\n]+" "" _host_compact
        "${HOST_FUNCTION}")
    string(REGEX MATCHALL "returnHostExitCode::success"
        _success_returns "${_host_compact}")
    list(LENGTH _success_returns _success_return_count)
    if(NOT _success_return_count EQUAL 1)
        set(${OUT_VALID} FALSE PARENT_SCOPE)
        set(${OUT_REASON} "success return must occur exactly once" PARENT_SCOPE)
        return()
    endif()

    set(${OUT_VALID} TRUE PARENT_SCOPE)
    set(${OUT_REASON} "" PARENT_SCOPE)
endfunction()
